### ISSUE TITLE
put zrbackup scripts in ansible

### ISSUE THREAD

**Issue by job** [NLNOG/ring-ansible#16]
This needs to move to ansible https://github.com/NLNOG/ring-puppet/blob/master/modules/backup/manifests/init.pp

**Comment by grizz** [comment]
Might be better off making this more generic and using it for infrastructure?

**Comment by netravnen** [comment]
@job @grizz no traction for this? or just stall issue?

**Comment by grizz** [comment]
Good question :) Just stalled I would guess, does infra have backup?

**Comment by rodecker** [comment]
Fixed with https://github.com/NLNOG/ring-ansible/commit/c2763013b01b4972de9d69dcc2b0bef21df41e16
